### ISSUE TITLE
Update README with new values for MPC

### ISSUE THREAD

**Issue by Kam0ss** [sonia-auv/control_library#13]
**Warning :** Before creating an issue or task, make sure that it does not already exists in the [issue tracker](../). Thank you.

## Expected Enhancement
The values for MPC modes in the README should be updated to adapt the telemetry and be able to use the simulation.

## Current Behavior
The README display only 0 and 1 as values for the MPC modes.

## Comments
This is blocking from 

## Environment Used
- Project version : I think this should be done in branch feature/SYS802, it seems to be the most up to date.
- docker-compose version : tested with sonia-deploy on local

**Comment by alamarre3** [comment]
mode list added to read me
