### ISSUE TITLE
Catkin_make failed with undefined reference

### ISSUE THREAD

**Issue by supertoto29** [sonia-auv/control_library#8]
**Warning :** Before creating an issue or task, make sure that it does not already exists in the [issue tracker](../). Thank you.

## Expected Behavior
Catkin_make compiles after generation C++ code from matlab.

## Current Behavior
Error at the end of the catkin_make `rtiostream_interface.c:222: undefined reference to `rtIOStreamBlockingSend'`

## Possible Solution
Verify the dependecy of the files since there is multiple files with the same name

## Environment Used
- Project version : 0.0.0
- Matlab version : R2021b

**Comment by supertoto29** [comment]
Waiting for update to R2022a

**Comment by alamarre3** [comment]
@supertoto29 Same issue appear in R2022a. I have found the problem and its not that bad. 

Every thing is documented on wikiJS [here](https://wiki.sonia.etsmtl.ca/en/software/Navigation-and-Control/Generate-Cpp-Code).
